### ISSUE TITLE
[SETTING] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by yeong0jae** [COINKIRI/coinkiri-server-demo#1]
## Description 📝
프로젝트 초기 세팅

## To-Do ☑️
- [x] pr 템플릿 세팅
- [x] issue 템플릿 세팅
- [x] commit 템플릿 세팅
