### ISSUE TITLE
[FEAT] : 유저 소셜 로그인 구현

### ISSUE THREAD

**Issue by yeong0jae** [COINKIRI/coinkiri-server-demo#10]
## Description 📝
OAuth2를 이용한 카카오, 네이버 회원가입 구현

## To-Do ☑️
- [x] User 엔티티 생성
- [x] OAuth2 로직 삭제
- [x] 안드로이드로부터 accessToken을 받고 스프링부트에서 JWT를 다루도록 변경
- [x] 소셜 로그아웃 구현
- [ ] refresh Token 관리
